#!/Users/arthurdercq/.nvm/versions/node/v16.15.1/bin/node

let fs = require("fs");
let Phrase = require("arthur_dercq_palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);
  }
});
